meals_data = [
    {
        "breakfast": [
            {"name": "Eggs & Toast", "ingredients": ["eggs", "whole-grain bread"], "recipe": "Fry eggs and serve with toasted bread."},
            {"name": "Pancakes & Fresh Fruit", "ingredients": ["pancakes", "fresh fruit"], "recipe": "Serve pancakes with a side of fresh fruit."},
            {"name": "Omelette & Avocado", "ingredients": ["eggs", "avocado"], "recipe": "Cook eggs into an omelette and serve with sliced avocado."},
            {"name": "Yogurt & Granola", "ingredients": ["yogurt", "granola"], "recipe": "Serve yogurt with a topping of granola."},
            {"name": "Smoothie & Nuts", "ingredients": ["smoothie", "nuts"], "recipe": "Blend a smoothie and pair with a handful of nuts."},
            {"name": "Bagel & Cream Cheese", "ingredients": ["bagel", "cream cheese"], "recipe": "Toast a bagel and spread with cream cheese."},
            {"name": "Avocado Toast & Eggs", "ingredients": ["avocado", "bread", "eggs"], "recipe": "Mash avocado on toasted bread and serve with poached eggs."},
            {"name": "Breakfast Burrito", "ingredients": ["tortilla", "eggs", "cheese", "salsa"], "recipe": "Wrap scrambled eggs, cheese, and salsa in a tortilla."},
            {"name": "French Toast & Maple Syrup", "ingredients": ["bread", "eggs", "maple syrup"], "recipe": "Dip bread in egg mix, cook, and drizzle with maple syrup."},
            {"name": "Chia Pudding & Fresh Berries", "ingredients": ["chia seeds", "milk", "berries"], "recipe": "Soak chia seeds in milk overnight and top with berries."},
            {"name": "Cereal & Milk", "ingredients": ["cereal", "milk"], "recipe": "Pour cereal into a bowl and add milk."},
            {"name": "Waffles & Syrup", "ingredients": ["waffles", "syrup"], "recipe": "Serve waffles with maple syrup."},
            {"name": "Avocado Smoothie", "ingredients": ["avocado", "milk", "honey"], "recipe": "Blend avocado, milk, and honey into a smoothie."},
            {"name": "Egg Muffins", "ingredients": ["eggs", "cheese", "vegetables"], "recipe": "Bake eggs with vegetables and cheese in a muffin tin."},
            {"name": "Apple Cinnamon Oatmeal", "ingredients": ["oats", "apple", "cinnamon"], "recipe": "Cook oatmeal and add apple and cinnamon."},
            {"name": "Fruit Salad", "ingredients": ["apple", "banana", "berries", "orange"], "recipe": "Chop and mix fresh fruits together."},
            {"name": "Bagel with Avocado & Tomato", "ingredients": ["bagel", "avocado", "tomato"], "recipe": "Spread mashed avocado on a toasted bagel and top with tomato slices."},
            {"name": "Poached Eggs & Spinach", "ingredients": ["eggs", "spinach"], "recipe": "Poach eggs and serve on a bed of spinach."},
            {"name": "Muffins & Fresh Juice", "ingredients": ["muffins", "juice"], "recipe": "Serve freshly baked muffins with a glass of juice."},
            {"name": "Tofu Scramble & Toast", "ingredients": ["tofu", "bread", "vegetables"], "recipe": "Scramble tofu with vegetables and serve with toast."}
        ],
        "lunch": [
            {"name": "Grilled Chicken Salad & Bread", "ingredients": ["chicken", "lettuce", "tomato", "bread"], "recipe": "Grill chicken and toss with salad; serve with bread."},
            {"name": "Caesar Salad & Garlic Bread", "ingredients": ["lettuce", "parmesan", "croutons", "garlic bread"], "recipe": "Toss Caesar salad and serve with garlic bread."},
            {"name": "Veggie Wrap & Fresh Juice", "ingredients": ["tortilla", "lettuce", "tomato", "carrot", "juice"], "recipe": "Wrap vegetables in a tortilla and serve with fresh juice."},
            {"name": "Chicken Wrap & Fries", "ingredients": ["chicken", "tortilla", "fries"], "recipe": "Wrap grilled chicken in a tortilla and serve with crispy fries."},
            {"name": "Quinoa Bowl & Hummus", "ingredients": ["quinoa", "vegetables", "hummus"], "recipe": "Serve quinoa bowl with a side of hummus."},
            {"name": "BLT Sandwich & Chips", "ingredients": ["bacon", "lettuce", "tomato", "bread"], "recipe": "Assemble bacon, lettuce, and tomato in bread and serve with chips."},
            {"name": "Vegetable Stir Fry & Noodles", "ingredients": ["vegetables", "soy sauce", "noodles"], "recipe": "Stir-fry vegetables and serve with cooked noodles."},
            {"name": "Turkey Club Sandwich", "ingredients": ["turkey", "bacon", "lettuce", "tomato", "bread"], "recipe": "Layer turkey, bacon, lettuce, and tomato in toasted bread."},
            {"name": "Sushi Rolls", "ingredients": ["rice", "nori", "fish", "vegetables"], "recipe": "Roll sushi rice and fillings in nori sheets."},
            {"name": "Minestrone Soup & Crackers", "ingredients": ["vegetables", "pasta", "broth", "crackers"], "recipe": "Simmer vegetables and pasta in broth; serve with crackers."},
            {"name": "Grilled Cheese & Tomato Soup", "ingredients": ["cheese", "bread", "tomato", "broth"], "recipe": "Grill cheese sandwich and serve with tomato soup."},
            {"name": "Pasta Salad & Chicken", "ingredients": ["pasta", "chicken", "vegetables"], "recipe": "Toss pasta, chicken, and vegetables in dressing."},
            {"name": "Falafel & Tzatziki", "ingredients": ["chickpeas", "garlic", "yogurt", "cucumber"], "recipe": "Serve falafel with a side of tzatziki."},
            {"name": "Burrito Bowl", "ingredients": ["rice", "beans", "chicken", "guacamole"], "recipe": "Layer rice, beans, chicken, and guacamole in a bowl."},
            {"name": "Chickpea Salad & Pita", "ingredients": ["chickpeas", "cucumber", "tomato", "pita"], "recipe": "Toss chickpeas, cucumber, and tomato in a salad; serve with pita."},
            {"name": "Poke Bowl", "ingredients": ["rice", "fish", "avocado", "seaweed"], "recipe": "Layer rice, fish, avocado, and seaweed in a bowl."},
            {"name": "Chicken Caesar Wrap", "ingredients": ["chicken", "lettuce", "parmesan", "wrap"], "recipe": "Wrap grilled chicken with Caesar salad ingredients."},
            {"name": "Egg Salad Sandwich", "ingredients": ["eggs", "bread", "mayonnaise"], "recipe": "Make an egg salad and serve in a sandwich."},
            {"name": "Hummus & Veggies", "ingredients": ["hummus", "carrots", "cucumber", "bell pepper"], "recipe": "Serve hummus with sliced vegetables."}
        ],
        "dinner": [
            {"name": "Steak & Mashed Potatoes", "ingredients": ["steak", "potatoes", "butter"], "recipe": "Grill steak and serve with creamy mashed potatoes."},
            {"name": "Fish Tacos & Coleslaw", "ingredients": ["fish", "tortilla", "cabbage", "coleslaw"], "recipe": "Grill fish and assemble tacos with coleslaw."},
            {"name": "Spaghetti Bolognese & Garlic Bread", "ingredients": ["spaghetti", "ground beef", "tomato sauce", "garlic bread"], "recipe": "Cook spaghetti with bolognese sauce and serve with garlic bread."},
            {"name": "Stir-fried Vegetables & Rice", "ingredients": ["vegetables", "soy sauce", "ginger", "rice"], "recipe": "Stir-fry vegetables and serve with rice."},
            {"name": "Grilled Chicken & Roasted Vegetables", "ingredients": ["chicken", "potatoes", "carrots", "seasonings"], "recipe": "Grill chicken and serve with roasted vegetables."},
            {"name": "Lasagna & Caesar Salad", "ingredients": ["pasta", "cheese", "tomato sauce", "ground beef"], "recipe": "Layer pasta, sauce, and cheese; bake and serve with salad."},
            {"name": "BBQ Ribs & Cornbread", "ingredients": ["ribs", "BBQ sauce", "cornbread"], "recipe": "Cook ribs in BBQ sauce and serve with cornbread."},
            {"name": "Pad Thai & Spring Rolls", "ingredients": ["noodles", "peanuts", "bean sprouts"], "recipe": "Stir-fry noodles with toppings; serve with spring rolls."},
            {"name": "Roast Beef & Yorkshire Pudding", "ingredients": ["beef", "flour", "eggs"], "recipe": "Roast beef and serve with Yorkshire pudding."},
            {"name": "Shrimp Scampi & Garlic Bread", "ingredients": ["shrimp", "butter", "garlic", "bread"], "recipe": "Sauté shrimp in garlic butter and serve with garlic bread."},
            {"name": "Vegetable Tacos", "ingredients": ["tortilla", "vegetables", "cheese", "guacamole"], "recipe": "Assemble tacos with roasted vegetables and toppings."},
            {"name": "Chicken Alfredo", "ingredients": ["chicken", "pasta", "cream", "cheese"], "recipe": "Cook chicken and serve with creamy Alfredo pasta."},
            {"name": "Beef Stew", "ingredients": ["beef", "potatoes", "carrots", "broth"], "recipe": "Simmer beef, potatoes, and carrots in broth to make stew."},
            {"name": "Grilled Salmon & Asparagus", "ingredients": ["salmon", "asparagus", "lemon"], "recipe": "Grill salmon and serve with steamed asparagus."},
            {"name": "Stuffed Peppers", "ingredients": ["peppers", "rice", "ground beef", "cheese"], "recipe": "Stuff peppers with rice and ground beef, then bake."},
            {"name": "Chicken Parmesan & Pasta", "ingredients": ["chicken", "bread crumbs", "tomato sauce", "pasta"], "recipe": "Bread and fry chicken, top with sauce and cheese, and serve with pasta."},
            {"name": "Vegetable Curry", "ingredients": ["vegetables", "coconut milk", "curry powder"], "recipe": "Simmer vegetables in coconut milk and curry powder."},
            {"name": "Pork Chops & Roasted Potatoes", "ingredients": ["pork", "potatoes", "seasonings"], "recipe": "Grill pork chops and serve with roasted potatoes."}
        ]
    }
]
